-- POC-001: IRONMAN Relational Data Simulator - Snowflake schema
-- Run as ACCOUNTADMIN (default on a trial account). seed.py executes this file automatically.
-- NOTE: Snowflake stores PRIMARY KEY / FOREIGN KEY constraints as metadata only (not enforced),
-- so seed.py generates data with guaranteed integrity and validate.py verifies it.

CREATE WAREHOUSE IF NOT EXISTS IRONMAN_WH
  WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS IRONMAN_POC;
CREATE SCHEMA IF NOT EXISTS IRONMAN_POC.CORE;

USE WAREHOUSE IRONMAN_WH;
USE DATABASE IRONMAN_POC;
USE SCHEMA CORE;

-- Drop in reverse dependency order so the script is re-runnable
DROP TABLE IF EXISTS RESULTS;
DROP TABLE IF EXISTS REGISTRATIONS;
DROP TABLE IF EXISTS RACES;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS ATHLETES;
DROP TABLE IF EXISTS LOCATIONS;

CREATE TABLE LOCATIONS (
  LOCATION_ID  NUMBER(5,0)   NOT NULL,
  CITY         VARCHAR(100)  NOT NULL,
  COUNTRY      VARCHAR(100)  NOT NULL,
  REGION       VARCHAR(50)   NOT NULL,
  CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE ATHLETES (
  ATHLETE_ID   NUMBER(8,0)   NOT NULL,
  FIRST_NAME   VARCHAR(100)  NOT NULL,
  LAST_NAME    VARCHAR(100)  NOT NULL,
  EMAIL        VARCHAR(200)  NOT NULL,
  GENDER       VARCHAR(1)    NOT NULL,   -- M / F
  BIRTH_DATE   DATE          NOT NULL,
  AGE_GROUP    VARCHAR(10)   NOT NULL,   -- e.g. M40-44 (as of 2026-09-01)
  NATIONALITY  VARCHAR(100)  NOT NULL,
  IS_PRO       BOOLEAN       NOT NULL,
  CONSTRAINT PK_ATHLETES PRIMARY KEY (ATHLETE_ID),
  CONSTRAINT UQ_ATHLETES_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE EVENTS (
  EVENT_ID                 NUMBER(5,0)   NOT NULL,
  EVENT_NAME               VARCHAR(200)  NOT NULL,
  EVENT_TYPE               VARCHAR(20)   NOT NULL,   -- IRONMAN / IRONMAN 70.3
  EVENT_DATE               DATE          NOT NULL,
  LOCATION_ID              NUMBER(5,0)   NOT NULL,
  REGISTRATION_OPEN_DATE   DATE          NOT NULL,
  REGISTRATION_CLOSE_DATE  DATE          NOT NULL,
  CAPACITY                 NUMBER(6,0)   NOT NULL,
  STATUS                   VARCHAR(20)   NOT NULL,   -- COMPLETED / UPCOMING
  CONSTRAINT PK_EVENTS PRIMARY KEY (EVENT_ID),
  CONSTRAINT FK_EVENTS_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID)
);

CREATE TABLE RACES (
  RACE_ID           NUMBER(6,0)   NOT NULL,
  EVENT_ID          NUMBER(5,0)   NOT NULL,
  RACE_NAME         VARCHAR(250)  NOT NULL,
  CATEGORY          VARCHAR(20)   NOT NULL,   -- AGE_GROUP / PRO
  DISTANCE_TYPE     VARCHAR(20)   NOT NULL,   -- FULL / HALF
  SWIM_KM           NUMBER(6,2)   NOT NULL,
  BIKE_KM           NUMBER(6,2)   NOT NULL,
  RUN_KM            NUMBER(6,2)   NOT NULL,
  START_TIME        TIMESTAMP_NTZ NOT NULL,
  CONSTRAINT PK_RACES PRIMARY KEY (RACE_ID),
  CONSTRAINT FK_RACES_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS (EVENT_ID)
);

CREATE TABLE REGISTRATIONS (
  REGISTRATION_ID    NUMBER(9,0)   NOT NULL,
  ATHLETE_ID         NUMBER(8,0)   NOT NULL,
  RACE_ID            NUMBER(6,0)   NOT NULL,
  REGISTRATION_DATE  DATE          NOT NULL,
  BIB_NUMBER         NUMBER(5,0),              -- NULL when cancelled
  STATUS             VARCHAR(20)   NOT NULL,   -- CONFIRMED / CANCELLED
  FEE_USD            NUMBER(8,2)   NOT NULL,
  CONSTRAINT PK_REGISTRATIONS PRIMARY KEY (REGISTRATION_ID),
  CONSTRAINT UQ_REG_ATHLETE_RACE UNIQUE (ATHLETE_ID, RACE_ID),
  CONSTRAINT FK_REG_ATHLETE FOREIGN KEY (ATHLETE_ID) REFERENCES ATHLETES (ATHLETE_ID),
  CONSTRAINT FK_REG_RACE FOREIGN KEY (RACE_ID) REFERENCES RACES (RACE_ID)
);

CREATE TABLE RESULTS (
  RESULT_ID        NUMBER(9,0)   NOT NULL,
  REGISTRATION_ID  NUMBER(9,0)   NOT NULL,
  RESULT_STATUS    VARCHAR(20)   NOT NULL,   -- FINISHED / DNF / DNS
  DNF_STAGE        VARCHAR(10),              -- SWIM / BIKE / RUN (DNF only)
  SWIM_SECONDS     NUMBER(7,0),
  T1_SECONDS       NUMBER(7,0),
  BIKE_SECONDS     NUMBER(7,0),
  T2_SECONDS       NUMBER(7,0),
  RUN_SECONDS      NUMBER(7,0),
  TOTAL_SECONDS    NUMBER(7,0),              -- FINISHED only
  OVERALL_RANK     NUMBER(5,0),              -- FINISHED only, rank within race
  GENDER_RANK      NUMBER(5,0),              -- FINISHED only, rank within race + gender
  CONSTRAINT PK_RESULTS PRIMARY KEY (RESULT_ID),
  CONSTRAINT UQ_RESULTS_REG UNIQUE (REGISTRATION_ID),
  CONSTRAINT FK_RESULTS_REG FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATIONS (REGISTRATION_ID)
);
